config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'articles#index'

  # get '/news_sources/new', to: 'news_sources#new'
  # get '/news_sources/', to: 'news_sources#show', as: 'index'
  # post '/news_sources/new/create', to: 'news_sources#create'
  resources :news_sources
end

app/models/application_record.rb
# frozen_string_literal: true

# class model
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
end

app/models/news_source.rb
# frozen_string_literal: true

# class model
class NewsSource < ApplicationRecord
  validates :url, presence: true, length: { maximum: 50 }
  validates :title, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# class controller
class ArticlesController < ApplicationController
  def index
    arr = NewsFeeds::ParseBytebytego.new.call
    NewsFeeds::SaveArticles.new(arr).call
    @articles = Article.all
  end
end

app/controllers/news_sources_controller.rb
# frozen_string_literal: true

# class controller
class NewsSourcesController < ApplicationController
  def new
    @news_source = NewsSource.new
  end

  def show
    @news_source = NewsSource.find(params[:id])
  end

  def index
    @news_sources_list = NewsSource.all
  end

  def create
    @news_source = NewsSource.new(post_params)
    if @news_source.save
      redirect_to news_sources_path
    else
      get_errors
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @news_source = NewsSource.find(params[:id])
  end

  def update
    @news_source = NewsSource.find(params[:id])
    if @news_source.update(post_params)
      redirect_to news_sources_path
    else
      get_errors
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @news_source = NewsSource.find(params[:id])
    @news_source.destroy

    redirect_to news_sources_path, status: :see_other
  end

  private

  def post_params
    params.require(:news_source).permit(:url, :title, :isActive)
  end

  def errors
    errors = %i[url title].map { |field| @news_source.errors.full_messages_for(field) }.join("\n")
    flash.now[:error] = errors
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# class helper
module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

# class helper
module ArticlesHelper
end

app/helpers/news_sources_helper.rb
# frozen_string_literal: true

# class helper
module NewsSourcesHelper
end

app/views/articles/index.html.erb
<head>
  <%= stylesheet_link_tag "style.css" %>
</head>

<body>
  <% @articles.each do |article| %>
    <div class="">
      <div class="tab-content">
        <div class="block">
          <h3><%= article.title %></h3>
          <p><%= article.url %></p>
          <%= link_to "Перейти к статье", article.url %>
        </div>
      </div>
    </div>
  <% end %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyDevClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" %>
    <!--<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>-->
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/news_sources/_form.html.erb
<head>
  <%= stylesheet_link_tag "style.css" %>
</head>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, content_tag(:p, msg), class: "name" %>
<% end -%>
    
<%= form_with model: @news_source do |form|%>
  <div>
    <div class="formElement">
      <div class="element">
        <div class="mb-3">URL of the feed: </div>
        <div class="mb-3">Name: </div>
        <div class="mb-3">Activated: </div>
      </div>
      <div class="element">
        <div class="mb-3"><%= form.url_field :url %></div>
        <div class="mb-2"><%= form.text_field :title %></div>
        <div class="mb-3"><%= form.check_box :isActive %></div>
      </div>
    </div>
  
    <div><%= form.submit :class => 'btn btn-success' "Save"  %></div>
  </div>
<% end %>

app/views/news_sources/edit.html.erb
<head>
  <%= stylesheet_link_tag "style.css" %>
</head>
<body>

  <h1>Edit article</h1>
  <%= render "form", news_source: @news_source%>
</body>

app/views/news_sources/index.html.erb
<head>
  <%= stylesheet_link_tag "style.css" %>
</head>
<body>
    <h1 class="header">News Sources</h1>
    <div class="newSourceMain">
        <div class="newSourceBtn">
            <%= link_to "+ NEW SOURCE", new_news_source_path %>
        </div>
        <div>
            <ul class="list-group">
                <% @news_sources_list.each do |news_source| %>
                    <li class="list-group-item title" style="margin-top: 10px;" >
                        <div >
                            <%= news_source.title %>
                            <strong class=<%= news_source.isActive == true ? 'statusActive' : 'statusInActive' %>>
                                <%= news_source.isActive == true ? 'Active' : 'InActive' %>
                            </strong>
                        </div>
                        <div class="UDBtn">
                            <%= link_to "Edit", edit_news_source_path(news_source) %>
                            <%= link_to "Delete", news_source_path(news_source), data: {
                            turbo: true,
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                            } %>
                            <%= link_to "Open", news_source_path(news_source) %>
                        </div>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</body>

app/views/news_sources/new.html.erb
<head>
  <%= stylesheet_link_tag "style.css" %>
</head>
<body>
  <h1>Add news source</h1>

  <%= render "form", news_source: @news_source %>
</body>

app/views/news_sources/show.html.erb
<head>
  <%= stylesheet_link_tag "style.css" %>
</head>
<body>
  <h1 class="header">News Source</h1>
  <div class="NewsSourceInfo">
    <p>
      <strong>Title:</strong> <%= @news_source.title%>
    </p>
    <p>
      <strong>URL:</strong> <%= @news_source.url%>
    </p>
    <p>
      <strong>Status:</strong> <%= @news_source.isActive == true ? 'Active' : 'InActive' %> 
    </p>
    <div>
      <%= link_to "Back", news_sources_path %>
    </div>
  </div>
</body>